---

stages:
- download-stage
- build-stage
- publish-stage

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ''
  DOCKERHUB_CACHE: ${UV_HOST_HARBOR}/dockerhub_proxy_cache/
  LANG: C.UTF-8
  UV_APP_VERSION: 1.0.1
  UV_HOST_HARBOR: artifacts.knut.univention.de
  UV_HOST_INT: docker-registry.knut.univention.de
  SOUVAP_REGISTRY_HOST: registry.souvap-univention.de
  UV_IMAGE_NAME: dovecot-connector
  UV_PATH_HARBOR: ${UV_HOST_HARBOR}/upx/${UV_IMAGE_NAME}
  UV_PATH_INT: ${UV_HOST_INT}/${UV_IMAGE_NAME}
  SOUVAP_REGISTRY_PATH: ${SOUVAP_REGISTRY_HOST}/souvap/tooling/images/${UV_IMAGE_NAME}

default:
  before_script:
  - mkdir -p "${HOME}/.docker/"
  - echo "${DOCKER_AUTH_CONFIG}" > "${HOME}/.docker/config.json"

.dind:
  image: ${DOCKERHUB_CACHE}library/docker:20.10.12
  services:
  - name: ${UV_HOST_INT}/ucs/docker:dind
    alias: docker
  tags:
  - docker

download-job:
  image: ${DOCKERHUB_CACHE}library/alpine:3.16.2
  stage: download-stage
  interruptible: true
  before_script:
  - echo "Explicitly skip the default action docker login"
  script:
  - apk add --no-cache py3-dotenv~=0.19 py3-requests~=2.27
  - apk list
  - echo "GLDL_API_BASE_URL ${GLDL_API_BASE_URL}"
  - echo "GLDL_DL_PATH ${GLDL_DL_PATH}"
  - echo "GLDL_JOB_NAME ${GLDL_JOB_NAME}"
  - echo "GLDL_PROJECT_ID ${GLDL_PROJECT_ID}"
  - python3 get-artifact.py
  artifacts:
    paths:
    - python-doveadm.zip
    expire_in: 1 week

# build docker image and push SHA to harbor
build-job:
  stage: build-stage
  interruptible: true
  extends: .dind
  dependencies:
  - download-job
  script:
  - docker --version
  - apk add git
  - git --version
  - docker build
      --pull
      --build-arg "version=${UV_APP_VERSION}"
      --tag "${UV_IMAGE_NAME}:${CI_COMMIT_SHA}"
      --file Dockerfile
      .

  # push sha to uv-internal repo
  - docker tag
      "${UV_IMAGE_NAME}:${CI_COMMIT_SHA}"
      "${UV_PATH_INT}:${CI_COMMIT_SHA}"
  - docker push "${UV_PATH_INT}:${CI_COMMIT_SHA}"

  # push sha to harbor repo
  - docker tag
      "${UV_IMAGE_NAME}:${CI_COMMIT_SHA}"
      "${UV_PATH_HARBOR}:${CI_COMMIT_SHA}"
  - docker push "${UV_PATH_HARBOR}:${CI_COMMIT_SHA}"

  # push sha to souvap
  - mkdir -p "${HOME}/.docker/"
  - echo "${SOUVAP_DOCKER_AUTH_CONFIG}" > "${HOME}/.docker/config.json"
  - docker tag
      "${UV_IMAGE_NAME}:${CI_COMMIT_SHA}"
      "${SOUVAP_REGISTRY_PATH}:${CI_COMMIT_SHA}"
  - docker push "${SOUVAP_REGISTRY_PATH}:${CI_COMMIT_SHA}"


# push git-tag-name to harbor docker repo
push-tag-harbor-job:
  stage: publish-stage
  only:
  - tags
  extends: .dind
  script:
  - docker pull "${UV_PATH_HARBOR}:${CI_COMMIT_SHA}"
  - docker tag
      "${UV_PATH_HARBOR}:${CI_COMMIT_SHA}"
      "${UV_PATH_HARBOR}:${CI_COMMIT_REF_NAME}"
  - docker push "${UV_PATH_HARBOR}:${CI_COMMIT_REF_NAME}"

# push git-tag-name to internal docker repo
push-tag-intern-job:
  stage: publish-stage
  variables:
    GIT_STRATEGY: none
  only:
  - tags
  extends: .dind
  before_script:
  - echo "Explicitly skip the default action docker login"
  script:
  - docker pull "${UV_PATH_INT}:${CI_COMMIT_SHA}"
  - docker tag
      "${UV_PATH_INT}:${CI_COMMIT_SHA}"
      "${UV_PATH_INT}:${CI_COMMIT_REF_NAME}"
  - docker push "${UV_PATH_INT}:${CI_COMMIT_REF_NAME}"

push-tag-souvap-job:
  stage: publish-stage
  variables:
    GIT_STRATEGY: none
  only:
  - tags
  extends: .dind
  before_script:
  # - echo "Explicitly skip the default action docker login"
  - mkdir -p "${HOME}/.docker/"
  - echo "${SOUVAP_DOCKER_AUTH_CONFIG}" > "${HOME}/.docker/config.json"
  script:
  - docker pull "${SOUVAP_REGISTRY_PATH}:${CI_COMMIT_SHA}"
  - docker tag
      "${SOUVAP_REGISTRY_PATH}:${CI_COMMIT_SHA}"
      "${SOUVAP_REGISTRY_PATH}:${CI_COMMIT_REF_NAME}"
  - docker push "${SOUVAP_REGISTRY_PATH}:${CI_COMMIT_REF_NAME}"

...
