---

stages:
- lint
- prepare
- build
- test
- package
- publish

variables:
  SOUVAP_HELM_PROJECT_ID: 129
  SOUVAP_API_V4_URL: https://gitlab.souvap-univention.de/api/v4
  SOUVAP_DOCKER_ACCESS_USER: gitlab-ci-knut
  SOUVAP_HELM_ACCESS_USER: gitlab-ci-knut
  SOUVAP_DOCKER_ACCESS_TOKEN: ${SOUVAP_REGISTRY_TOKEN}
  SOUVAP_REGISTRY_HOST: registry.souvap-univention.de
  SOUVAP_REGISTRY_PATH: souvap/tooling/images/dovecot-connector
  SOUVAP_REGISTRY_REPO: ${SOUVAP_REGISTRY_HOST}/${SOUVAP_REGISTRY_PATH}


include:
  - project: univention/customers/dataport/upx/common-ci
    file:
      - defaults/souvap-workflow.yaml
      - templates/souvap.yaml
      - templates/kaniko.yaml
      - jobs/lint-pre-commit.yaml
      - jobs/package-and-publish-helm-charts.yaml


lint-pre-commit:
  before_script:
    # Compose lint would fail without the referenced env files
    - cp .env.example .env
    - cp .env.souvap.example .env.souvap


download-python-doveadm:
  image: ${DOCKERHUB_CACHE}library/alpine:3.16.2
  stage: prepare
  interruptible: true
  before_script:
  - echo "Explicitly skip the default action docker login"
  script:
  - apk add --no-cache py3-dotenv~=0.19 py3-requests~=2.27
  - apk list
  - echo "GLDL_API_BASE_URL ${GLDL_API_BASE_URL}"
  - echo "GLDL_DL_PATH ${GLDL_DL_PATH}"
  - echo "GLDL_JOB_NAME ${GLDL_JOB_NAME}"
  - echo "GLDL_PROJECT_ID ${GLDL_PROJECT_ID}"
  - python3 get-artifact.py
  artifacts:
    paths:
    - python-doveadm.zip
    expire_in: 1 week

build-standalone-job:
  stage: build
  needs:
    - job: download-python-doveadm
  extends: .kaniko
  variables:
    DOCKERFILE_PATH: "Dockerfile.souvap"
    KANIKO_ARGS: "--build-arg version=$UV_APP_VERSION"
    CI_REGISTRY_IMAGE: "$CI_REGISTRY_IMAGE"

push-image-souvap-standalone-job:
  stage: publish
  needs:
    - job: build-standalone-job
  extends: .push-image-souvap
  variables:
    CI_REGISTRY_IMAGE: "$CI_REGISTRY_IMAGE"
    SOUVAP_IMAGE_NAME: "dovecot-connector"


publish-helm-charts-souvap:
  extends: .publish-helm-charts-souvap

...
