---
include:
  - project: "univention/customers/dataport/upx/common-ci"
    ref: "v1.11.1"
    file:
      - "defaults/stages.yaml"
      - "defaults/souvap-workflow.yaml"
      - "templates/souvap.yaml"
      - "jobs/lint-pre-commit.yaml"
      - "jobs/lint-commit-messages.yaml"
      - "jobs/semantic-release-env.yaml"
      - "jobs/container-build-souvap.yaml"
      - "jobs/package-and-publish-helm-charts.yaml"

variables:
  SOUVAP_HELM_PROJECT_ID: 129
  SOUVAP_DOCKER_ACCESS_TOKEN: ${SOUVAP_REGISTRY_TOKEN}
  SOUVAP_REGISTRY_PATH: souvap/tooling/images/dovecot-connector
  IMAGE_NAME: "dovecot-connector"

download-python-doveadm:
  image: ${DOCKERHUB_CACHE}library/alpine:3.16.2
  stage: prepare
  interruptible: true
  before_script:
    - echo "Explicitly skip the default action docker login"
  script:
    - |
      apk add --no-cache py3-dotenv~=0.19 py3-requests~=2.27
      apk list
      echo "GLDL_API_BASE_URL ${GLDL_API_BASE_URL}"
      echo "GLDL_DL_PATH ${GLDL_DL_PATH}"
      echo "GLDL_PROJECT_ID ${GLDL_PROJECT_ID}"
      echo "GLDL_JOB_NAME ${GLDL_JOB_NAME}"
      python3 get-artifact.py
  artifacts:
    paths:
      - python-doveadm.zip
    expire_in: 1 week

container-build:
  variables:
    KANIKO_BUILD_CONTEXT: "$CI_PROJECT_DIR"
    DOCKERFILE_PATH: "docker/dovecot-connector/Dockerfile.souvap"
    KANIKO_ARGS: "--build-arg version=${SEMANTIC_VERSION}"

publish-helm-charts-souvap:
  extends: .publish-helm-charts-souvap
...
