#!/usr/bin/env bash

# Helper to push the app-dir to the Appcenter
#
# Copyright (C) 2022 Univention GmbH
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# SPDX-License-Identifier: AGPL-3.0-or-later
# SPDX-License-Name: GNU Affero General Public License v3.0 or later
# SPDX-License-URL: https://spdx.org/licenses/AGPL-3.0-or-later.html

set -e
set -x

APP_ID="dovecot-connector"

selfservice () {
	local uri="https://provider-portal.software-univention.de/appcenter-selfservice/univention-appcenter-control"
	local first=$1
	shift

	# USERNAME="$USER"
	# [ -e "$HOME/.univention-appcenter-user" ] && USERNAME="$(< $HOME/.univention-appcenter-user)"

	# PWDFILE="~/.selfservicepwd"
	# [ -e "$HOME/.univention-appcenter-pwd" ] && PWDFILE="$HOME/.univention-appcenter-pwd"

	# curl -sSfL "$uri" | python2 - "$first" --username=${USERNAME} --pwdfile=${PWDFILE} "$@"
    curl -sSfL "$uri" | python3 - "$first" "$@"
}

die () {
	echo "$@"
	exit 0
}

[ "$IGN_GIT" != "true" ] && test -n "$(git status -s)" && die "Changes in repo, do not upload app! (to override: IGN_GIT=true)"

APP_VERSION="$(grep ^Version app/ini | awk '{ print $3 }')"
APP_VERSION_STRING="4.4/${APP_ID}=${APP_VERSION}"
echo "App version in source code is: '${APP_VERSION}'."
echo "The app version string used for the upload is '${APP_VERSION_STRING}'."

selfservice upload "${APP_VERSION_STRING}" app/ini app/listener_trigger app/README_DE app/README_EN app/settings
