---
{{ include "common.configMap" (dict "top" . "overrides" "ldap-server.configMap") }}

{{- define "ldap-server.configMap" }}
data:
  {{ with .Values.dovecotConnector }}
  # Variables for Univention Directory Listener
  LDAP_HOST: "{{ .ldapHost }}"
  LDAP_PORT: "{{ .ldapPort }}"
  LDAP_BASE_DN: "{{ .ldapBaseDn }}"
  LDAP_HOST_DN: "{{ .ldapHostDn }}"
  NOTIFIER_SERVER: "{{ .notifierServer }}"
  DEBUG_LEVEL: "{{ .debugLevel }}"
  LDAP_PASSWORD: "{{ .ldapPassword }}"
  LDAP_PASSWORD_FILE: "{{ .ldapPasswordFile }}"
  CA_CERT: "{{ .caCert }}"
  CA_CERT_FILE: "{{ .caCertFile }}"
  TLS_MODE: "{{ .tlsMode }}"
  # Variables for Dovecot Connector
  DCC_ADM_URI: "{{ .dccAdmUri }}"
  DCC_ADM_HOST: "{{ .dccAdmHost }}"
  DCC_ADM_PORT: "{{ .dccAdmPort }}"
  DCC_ADM_USERNAME: "{{ .dccAdmUsername }}"
  DCC_ADM_PASSWORD: "{{ .dccAdmPassword }}"
  DCC_DC_VMAIL_TEMPLATE: "{{ .dccDcVmailTemplate }}"
  DCC_ADM_ACCEPTED_EXIT_CODES: "{{ .dccAdmAcceptedExitCodes }}"
  DCC_LOGLEVEL: "{{ .dccLoglevel }}"
  {{ end }}
{{- end }}

...
