---

apiVersion: "v1"
kind: ConfigMap
metadata:
  name: '{{ include "common.names.fullname" . }}'
data:
  {{ with .Values.dovecot_connector }}
  DOMAIN_NAME: "{{ .domainName }}"
  LDAP_PORT: "{{ .ldapPort }}"
  LDAP_HOST: "{{ .ldapHost }}"
  LDAP_BASE_DN: "{{ .ldapBaseDn }}"
  LDAP_HOST_DN: "{{ .ldapHostDn }}"
  NOTIFIER_SERVER: "{{ .notifierServer }}"
  DEBUG_LEVEL: "{{ .debugLevel }}"
  LDAP_BIND_SECRET: "{{ .ldapBindSecret }}"
  CA_CERT_FILE: "{{ .caCertFile }}"
  CERT_PEM_FILE: "{{ .certPemFile }}"
  DCC_ADM_URI: "{{ .dccAdmUri }}"
  DCC_ADM_HOST: "{{ .dccAdmHost }}"
  DCC_ADM_PORT: "{{ .dccAdmPort }}"
  DCC_ADM_USERNAME: "{{ .dccAdmUsername }}"
  DCC_ADM_PASSWORD: "{{ .dccAdmPassword }}"
  DCC_DC_VMAIL_TEMPLATE: "{{ .dccDcVmailTemplate }}"
  DCC_ADM_ACCEPTED_EXIT_CODES: "{{ .dccAdmAcceptedExitCodes }}"
  DCC_LOGLEVEL: "{{ .dccLoglevel }}"
  {{ end }}
...
