---

apiVersion: "v1"
kind: "Secret"
type: "Opaque"
metadata:
  name: '{{ include "common.names.fullname" . }}'
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
data:
  ldap_secret: '{{ .Values.dovecotConnector.authLdapSecret | quote }}'
  ca_cert: '{{ .Values.dovecotConnector.caCert | quote }}'

...
