apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: '{{ include "common.names.fullname" . }}'
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
data:
  ldap_secret: {{ .Values.dovecot_connector.authLdapSecret | quote }}
  ca_cert: {{ .Values.dovecot_connector.caCert | quote }}
  cert_pem: {{ .Values.dovecot_connector.certPem | quote }}
