---
# Default values for dovecot-connector.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## Global values
affinity: {}
environment: {}
fullnameOverride: ""
nameOverride: ""
nodeSelector: {}
podAnnotations: {}
podSecurityContext: {}
replicaCount: 1
securityContext: {}
tolerations: []
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80


## Application-specific variables
dovecotConnector:
  # Variables for Univention Directory Listener
  # -- LDAP Server Domain Name
  ldapHost: null
  # -- LDAP Server Port
  ldapPort: 389
  # -- Will add a mapping from "ldapHost" to "ldapHostIp" into "/etc/hosts" if set
  ldapHostIp: null
  # -- LDAP Base Distinguished Name
  ldapBaseDn: null
  # -- LDAP Host Distinguished Name
  ldapHostDn: null
  # -- Defaults to "ldapHost" if not set.
  notifierServer: null
  # -- UDL-Debug level (1-5)
  debugLevel: 3
  # -- LDAP password for `cn=admin`. Will be written to "ldapPasswordFile" if set.
  authLdapSecret: null
  # -- The path to the "ldapPasswordFile" docker secret or a plain file
  ldapBindSecret: "/run/secrets/ldap_secret"
  # -- CA root certificate. Optional; will be written to "caCertFile" if set.
  caCert: null
  # -- The path to the "caCertFile" docker secret or a plain file.
  caCertFile: "/run/secrets/ca_cert"

  # Variables for Dovecot Connector
  # -- Template for the python dovecot-connector script.
  dccAdmUri: "http://{dcc_adm_host}:{dcc_adm_port}/doveadm/v1"
  # -- Host where the doveadm HTTP API is hosted.
  dccAdmHost: null
  # -- Host where the doveadm HTTP API is exposed.
  dccAdmPort: "80"
  # -- doveadm user, normally `doveadm` or specified under `doveadm_username` at `dovecont.conf`.
  dccAdmUsername: null
  # -- doveadm password, usually under `doveadm_password` on the `dovecot.conf` file.
  dccAdmPassword: null
  # -- doveadm password, usually under `doveadm_password` on the `dovecot.conf` file, with options `domain`, `username`, `email`, `uuid`.
  dccDcVmailTemplate: "/var/spool/dovecot/private/{domain}/{username}"
  # -- DoveAdm exit codes which will be considered as successful
  # [dovecot specs](https://doc.dovecot.org/admin_manual/error_codes/)
  dccAdmAcceptedExitCodes: "0 2 68 75"
  # -- Log level
  dccLoglevel: "INFO"

# -- Kubernetes ingress
ingress:
  # -- Set this to `true` in order to enable the installation on Ingress related objects.
  enabled: false

## Docker image
image:
  registry: "registry.souvap-univention.de"
  repository: "souvap/tooling/images/dovecot-connector"
  tag: "1.0.2"
  imagePullPolicy: "Always"

## Container deployment probes
probes:
  liveness:
    enabled: true
    initialDelaySeconds: 120
    timeoutSeconds: 3
    periodSeconds: 30
    failureThreshold: 3
    successThreshold: 1

  readiness:
    enabled: true
    initialDelaySeconds: 30
    timeoutSeconds: 3
    periodSeconds: 15
    failureThreshold: 30
    successThreshold: 1

## Deployment resources
resources: {}

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""
